    vc_installpath: "http://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x86.exe"
    php_installpath: "http://windows.php.net/downloads/releases/php-5.6.2-nts-Win32-VC11-x64.zip"