---
  - name: webserver
    action: win_feature name="Web-Server","Web-Mgmt-Tools","web-Default-Doc","Web-Dir-Browsing","Web-Http-Errors","Web-Static-Content","Web-Http-Logging","web-Stat-Compression","web-Filtering","web-CGI","web-ISAPI-Ext","web-ISAPI-Filter" state=present restart=False

# Download PHP thingy if it's not already on disk
  - name: Verify PHP thingy
    action: win_stat path="C:\php.zip"
    register: phpfile

  - name: Download PHP
    action: win_get_url dest="C:\php.zip" url="http://windows.php.net/downloads/releases/php-5.5.14-nts-Win32-VC11-x64.zip"
    when: phpfile.stat.exists == false

  - name: Verify PHP folder
    action: win_stat path="C:\php"
    register: phpfolder

  - name: Unzip PHP folder
    action: script extractfile.ps1
    when: phpfolder.stat.isdir == false and phpfolder.stat.exists == false

  - name: Verify VC2012 Redist
    action: win_stat path="C:\vcredist_x64.exe"
    register: vcredistfile

  - name: Download VC2012 Redist
    action: win_get_url dest="C:\vcredist_x64.exe" url="http://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x64.exe"
    when: vcredistfile.stat.exists == false

  - name: Install VC 2012 Redist
    action: script installvc2012.ps1

  - name: Configure PHP for IIS
    action: script configurephp.ps1
  - name: Configure PHP for IIS
    action: script configuredefaultdoc.ps1

